stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

test:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - pytest tests/

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE

deploy_staging:
  stage: deploy
  image: alpine/helm:3.7.0
  script:
    - helm upgrade --install mlops-staging ./infrastructure/charts --values ./infrastructure/values-staging.yaml
  environment:
    name: staging
    url: https://staging.example.com

monitoring:
  stage: deploy
  image: alpine/k8s:1.21.2
  script:
    - kubectl apply -f ./monitoring/prometheus.yaml
    - kubectl apply -f ./monitoring/grafana.yaml
  when: manual